INSERT INTO Version (ThisInstanceQPId) values ('b61e7786-891f-4883-8d55-ef2b9abacfad');
INSERT INTO PrintedDrawing (id,AdditionalChanges,Description,DrawingNumber,Location,Name,Version) values ('5','none','Sample QIF elements','#1','Cabinet 17, Drawer 3','sheet2_solid4','1.0.0');
INSERT INTO DefinitionExternal (id,_PrintedDrawing) values ('6',1);
INSERT INTO Part (id,_DefinitionExternal,Description,ModelNumber,Name,QPId,Version) values ('1',1,'Wing Mirror Re-enforcement','QM_X_123456','WING_MIR_REENF','2bbeb82a-96bf-4f1e-a327-4ba3500490e1','1.02');
INSERT INTO PartSet (N,__Part) values ('1','{1}');
INSERT INTO ElementReference (Id) values (1);
INSERT INTO Component (id,_Part,QPId) values ('2',1,'af4d1612-8918-4a69-a716-709beee7a953');
INSERT INTO ComponentSet (N,__Component) values ('1','{1}');
INSERT INTO ArrayReference (N,Id) values ('1','{"2"}');
INSERT INTO AsmPath (id,_ComponentIds) values ('3',6);
INSERT INTO AsmPaths (N,__AsmPath) values ('1','{1}');
INSERT INTO Product (_AsmPaths,_ComponentSet,_PartSet) values (1,1,1);
INSERT INTO QPIdFullReference (ItemQPId) values ('9fcebcb6-99da-44f9-b997-2ba76fd438dd');
INSERT INTO PhysicalAddress (ElectronicMailAddress,FacsimileNumber,PostalCode,Region,Street,StreetNumber,TelephoneNumber,Town) values ('support@originintl.com','416 410 8313','L4C 9B8','Ontario','Baynards Lane','72','1-800-269-2509','Richmond Hill');
INSERT INTO Organization (_Address,Name) values (1,'Origin International');
INSERT INTO FormalStandard (FormalStandardEnum) values ('ASME-Y14.5-1994');
INSERT INTO ArrayReference (N,Id) values ('1','{"3"}');
INSERT INTO PreInspectionTraceability (_AsmPathIds,_FormalStandard,_InspectingOrganization,InspectionMode,InspectionScope,PurchaseOrderNumber,_ReferencedQIFPlanInstance,ReportNumber,SupplierCode) values (4,3,1,'FAI_Full','DETAIL','PO123456',1,'QIF 1','North_Fab');
INSERT INTO PointFeatureActual (id,FeatureItemId,Location) values ('20',19,'{2466.9,774.31,944.84}');
INSERT INTO PointFeatureActual (id,FeatureItemId,Location) values ('20',19,'{2466.9,774.31,944.84}');
INSERT INTO EdgePointFeatureActual (id,FeatureItemId,Location,Normal) values ('10',9,'{2460.72,770.62,944.98}','{-0.735465884156759,-0.307902932144912,0.603560864882807}');
INSERT INTO CircleFeatureActual (id,Diameter,FeatureItemId,Location,Normal) values ('44',9.499476,43,'{2434.01,801.52505599193,889.98}','{0.0558150216639657,-0.907624351305543,-0.416056150385791}');
INSERT INTO CircleFeatureActual (id,Diameter,FeatureItemId,Location,Normal) values ('44',9.499476,43,'{2434.01,801.52505599193,889.98}','{0.0558150216639657,-0.907624351305543,-0.416056150385791}');
INSERT INTO CircleFeatureActual (id,Diameter,FeatureItemId,Location,Normal) values ('44',9.499476,43,'{2434.01,801.52505599193,889.98}','{0.0558150216639657,-0.907624351305543,-0.416056150385791}');
INSERT INTO FeatureActuals (__CircleFeatureActual,__EdgePointFeatureActual,__PointFeatureActual) values ('{1,2,3}','{1}','{1,2}');
INSERT INTO MeasuredFeatures (_FeatureActuals) values (1);
INSERT INTO CharacteristicStatus (CharacteristicStatusEnum) values ('PASS');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"44"}');
INSERT INTO PositionCharacteristicActual (id,CharacteristicItemId,_FeatureActualIds,NonConformanceDesignator,_Status,Value) values ('57',55,109,'NA',21,0.897298445619386);
INSERT INTO CharacteristicStatus (CharacteristicStatusEnum) values ('PASS');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"44"}');
INSERT INTO PositionCharacteristicActual (id,CharacteristicItemId,_FeatureActualIds,NonConformanceDesignator,_Status,Value) values ('57',55,107,'NA',19,0.897298445619386);
INSERT INTO CharacteristicStatus (CharacteristicStatusEnum) values ('PASS');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"10"}');
INSERT INTO PointProfileCharacteristicActual (id,CharacteristicItemId,_FeatureActualIds,NonConformanceDesignator,_Status,Value) values ('16',14,105,'NA',17,-0.020323885080472);
INSERT INTO CharacteristicStatus (CharacteristicStatusEnum) values ('PASS');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"10"}');
INSERT INTO PointProfileCharacteristicActual (id,CharacteristicItemId,_FeatureActualIds,NonConformanceDesignator,_Status,Value) values ('16',14,103,'NA',15,-0.020323885080472);
INSERT INTO OfCoordinatesType (CoordinateEnum) values ('CARTESIAN_3D');
INSERT INTO CharacteristicStatus (CharacteristicStatusEnum) values ('BASIC');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"20"}');
INSERT INTO LinearCoordinateCharacteristicActual (id,CharacteristicItemId,_FeatureActualIds,NonConformanceDesignator,_Status,_TypeOfCoordinates,Value) values ('24',23,101,'NA',13,5,2466.9000000000001);
INSERT INTO OfCoordinatesType (CoordinateEnum) values ('CARTESIAN_3D');
INSERT INTO CharacteristicStatus (CharacteristicStatusEnum) values ('BASIC');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"20"}');
INSERT INTO LinearCoordinateCharacteristicActual (id,CharacteristicItemId,_FeatureActualIds,NonConformanceDesignator,_Status,_TypeOfCoordinates,Value) values ('24',23,99,'NA',11,3,2466.9000000000001);
INSERT INTO OfCoordinatesType (CoordinateEnum) values ('CARTESIAN_3D');
INSERT INTO CharacteristicStatus (CharacteristicStatusEnum) values ('BASIC');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"20"}');
INSERT INTO LinearCoordinateCharacteristicActual (id,CharacteristicItemId,_FeatureActualIds,NonConformanceDesignator,_Status,_TypeOfCoordinates,Value) values ('24',23,97,'NA',9,1,2466.9000000000001);
INSERT INTO CharacteristicStatus (CharacteristicStatusEnum) values ('PASS');
INSERT INTO ArrayReferenceFull (N,Id) values ('2','{"61","61"}');
INSERT INTO DistanceBetweenCharacteristicActual (id,CharacteristicItemId,_FeatureActualIds,_Status,Value) values ('85',84,95,7,81.220808617516994);
INSERT INTO CharacteristicStatus (CharacteristicStatusEnum) values ('FAIL');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"44"}');
INSERT INTO DiameterCharacteristicActual (id,CharacteristicItemId,_FeatureActualIds,NonConformanceDesignator,_Status,Value) values ('48',47,93,'1234',5,9.499476);
INSERT INTO CharacteristicStatus (CharacteristicStatusEnum) values ('FAIL');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"44"}');
INSERT INTO DiameterCharacteristicActual (id,CharacteristicItemId,_FeatureActualIds,NonConformanceDesignator,_Status,Value) values ('48',47,91,'1234',3,9.499476);
INSERT INTO CharacteristicStatus (CharacteristicStatusEnum) values ('FAIL');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"44"}');
INSERT INTO DiameterCharacteristicActual (id,CharacteristicItemId,_FeatureActualIds,NonConformanceDesignator,_Status,Value) values ('48',47,89,'1234',1,9.499476);
INSERT INTO CharacteristicActuals (__DiameterCharacteristicActual,__DistanceBetweenCharacteristicActual,__LinearCoordinateCharacteristicActual,__PointProfileCharacteristicActual,__PositionCharacteristicActual) values ('{1,2,3}','{1}','{1,2,3}','{1,2}','{1,2}');
INSERT INTO MeasuredCharacteristics (_CharacteristicActuals) values (1);
INSERT INTO InspectionStatus (InspectionStatusEnum) values ('FAIL');
INSERT INTO FileSpec (OtherFileSpec) values ('res');
INSERT INTO ExternalFileReference (Description,_FileSpec,URI) values ('Zeiss Umess CMM Results',1,'C:\R19_parts\5802804.res');
INSERT INTO ArrayReference (N,Id) values ('1','{"4"}');
INSERT INTO MeasurementResults (id,_ActualComponentIds,__ExternalFileReference,_InspectionStatus,_MeasuredCharacteristics,_MeasuredFeatures,ThisResultsInstanceQPId) values ('86',1,'{1}',4,1,1,'8521ff0f-4c05-4f13-a2be-1386190f75a6');
INSERT INTO Employee (EmployeeId,Name) values ('123-456','John Doe');
INSERT INTO InspectionTraceability (ReportPreparationDate,_ReportPreparer) values ('2014-07-30 11:14:06',1);
INSERT INTO InspectionStatus (InspectionStatusEnum) values ('FAIL');
INSERT INTO ActualComponent (id,AsmPathId,SerialNumber,_Status) values ('4',3,'Run 3, Bin 17',1);
INSERT INTO ActualComponentSet (N,__ActualComponent) values ('1','{1}');
INSERT INTO MeasurementsResults (__ActualComponentSet,_InspectionTraceability,__MeasurementResults) values ('{1}',1,'{1}');
INSERT INTO MeasurementDevice (id,Name) values ('15','CMM');
INSERT INTO MeasurementDevice (id,Name) values ('15','CMM');
INSERT INTO MeasurementDevice (id,Name) values ('15','CMM');
INSERT INTO MeasurementDevices (__MeasurementDevice) values ('{1,2,3}');
INSERT INTO MeasurementResources (_MeasurementDevices) values (1);
INSERT INTO Application (AddonName,AddonOrganization,Name) values ('CheckMate 14','Origin International Inc.','Solidworks 2014');
INSERT INTO QIFDocumentHeader (_Application) values (1);
INSERT INTO UnitConversion (Factor) values (0.001);
INSERT INTO LinearUnit (SIUnitName,_UnitConversion,UnitName) values ('meter',3,'mm');
INSERT INTO UnitConversion (Factor) values (0.017453292519943);
INSERT INTO AngularUnit (SIUnitName,_UnitConversion,UnitName) values ('radian',1,'degree');
INSERT INTO PrimaryUnits (_AngularUnit,_LinearUnit) values (1,1);
INSERT INTO FileUnits (_PrimaryUnits) values (1);
INSERT INTO PointFeatureNominal (id,FeatureDefinitionId,Location,Normal) values ('18',17,'{2466.72924804688,774.269897460938,945.002746582031}','{0.731520704665031,0.146124942551,-0.665976696146977}');
INSERT INTO PointFeatureNominal (id,FeatureDefinitionId,Location,Normal) values ('18',17,'{2466.72924804688,774.269897460938,945.002746582031}','{0.731520704665031,0.146124942551,-0.665976696146977}');
INSERT INTO EdgePointFeatureNominal (id,AdjacentNormal,FeatureDefinitionId,Location,Normal) values ('8','{0.0411800179070265,-0.909449806293278,-0.413769568671133}',7,'{2460.7099609375,770.604614257813,944.993591308594}','{-0.735465884156759,-0.307902932144912,0.603560864882807}');
INSERT INTO CircleFeatureNominal (id,FeatureDefinitionId,Location,Normal) values ('42',41,'{0.0558150216639657,-0.907624351305543,-0.416056150385791}','{2433.974609375,800.617431640625,890.049621582031}');
INSERT INTO CircleFeatureNominal (id,FeatureDefinitionId,Location,Normal) values ('42',41,'{0.0558150216639657,-0.907624351305543,-0.416056150385791}','{2433.974609375,800.617431640625,890.049621582031}');
INSERT INTO CircleFeatureNominal (id,FeatureDefinitionId,Location,Normal) values ('42',41,'{0.0558150216639657,-0.907624351305543,-0.416056150385791}','{2433.974609375,800.617431640625,890.049621582031}');
INSERT INTO FeatureNominals (__CircleFeatureNominal,__EdgePointFeatureNominal,__PointFeatureNominal) values ('{1,2,3}','{1}','{1,2}');
INSERT INTO PointChecked (_Measured) values (0);
INSERT INTO PointCheckedFeature (_CheckDetails) values (5);
INSERT INTO PointActualDetermination (_Checked) values (4);
INSERT INTO AttributeStr (value,name) values ('A point on a surface with coordinate characteristics','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{71}');
INSERT INTO PointFeatureItem (id,_Attributes,_DeterminationMode,FeatureName,FeatureNominalId,QPId) values ('19',55,3,'SURF1',18,'263c98a7-9786-4408-b62f-dda79a07daad');
INSERT INTO PointChecked (_Measured) values (0);
INSERT INTO PointCheckedFeature (_CheckDetails) values (1);
INSERT INTO PointActualDetermination (_Checked) values (1);
INSERT INTO AttributeStr (value,name) values ('A point on a surface with coordinate characteristics','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{68}');
INSERT INTO PointFeatureItem (id,_Attributes,_DeterminationMode,FeatureName,FeatureNominalId,QPId) values ('19',53,1,'SURF1',18,'263c98a7-9786-4408-b62f-dda79a07daad');
INSERT INTO EdgePointChecked (_Measured) values (0);
INSERT INTO EdgePointCheckedFeature (_CheckDetails) values (1);
INSERT INTO EdgePointActualDetermination (_Checked) values (1);
INSERT INTO AttributeStr (value,name) values ('An edge point with uniform profile characteristic','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{65}');
INSERT INTO EdgePointFeatureItem (id,_Attributes,_DeterminationMode,FeatureName,FeatureNominalId,QPId) values ('9',51,1,'TRIM1',8,'aeba4615-65db-4f7d-a2e8-a7928c80117f');
INSERT INTO CircleChecked (_Measured) values (0);
INSERT INTO CircleCheckedFeature (_CheckDetails) values (9);
INSERT INTO CircleActualDetermination (_Checked) values (7);
INSERT INTO AttributeStr (value,name) values ('A hole with position and gage-pin diameter','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{62}');
INSERT INTO CircleFeatureItem (id,_Attributes,_DeterminationMode,FeatureName,FeatureNominalId,QPId) values ('43',49,5,'HOLE1',42,'f29bb618-e50d-4dbb-b4b4-83b28755c741');
INSERT INTO CircleChecked (_Measured) values (0);
INSERT INTO CircleCheckedFeature (_CheckDetails) values (5);
INSERT INTO CircleActualDetermination (_Checked) values (4);
INSERT INTO AttributeStr (value,name) values ('A hole with position and gage-pin diameter','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{59}');
INSERT INTO CircleFeatureItem (id,_Attributes,_DeterminationMode,FeatureName,FeatureNominalId,QPId) values ('43',47,3,'HOLE1',42,'f29bb618-e50d-4dbb-b4b4-83b28755c741');
INSERT INTO CircleChecked (_Measured) values (0);
INSERT INTO CircleCheckedFeature (_CheckDetails) values (1);
INSERT INTO CircleActualDetermination (_Checked) values (1);
INSERT INTO AttributeStr (value,name) values ('A hole with position and gage-pin diameter','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{56}');
INSERT INTO CircleFeatureItem (id,_Attributes,_DeterminationMode,FeatureName,FeatureNominalId,QPId) values ('43',45,1,'HOLE1',42,'f29bb618-e50d-4dbb-b4b4-83b28755c741');
INSERT INTO FeatureItems (__CircleFeatureItem,__EdgePointFeatureItem,__PointFeatureItem) values ('{1,2,3}','{1}','{1,2}');
INSERT INTO PointFeatureDefinition (id) values ('17');
INSERT INTO PointFeatureDefinition (id) values ('17');
INSERT INTO EdgePointFeatureDefinition (id,InternalExternal) values ('7','EXTERNAL');
INSERT INTO CircleFeatureDefinition (id,Diameter,InternalExternal) values ('41',10,'INTERNAL');
INSERT INTO CircleFeatureDefinition (id,Diameter,InternalExternal) values ('41',10,'INTERNAL');
INSERT INTO CircleFeatureDefinition (id,Diameter,InternalExternal) values ('41',10,'INTERNAL');
INSERT INTO FeatureDefinitions (__CircleFeatureDefinition,__EdgePointFeatureDefinition,__PointFeatureDefinition) values ('{1,2,3}','{1}','{1,2}');
INSERT INTO FeatureAspectsLists (_FeatureDefinitions,_FeatureItems,_FeatureNominals) values (1,1,1);
INSERT INTO DatumReferenceFrame (id) values ('12');
INSERT INTO DatumReferenceFrame (id) values ('12');
INSERT INTO DatumReferenceFrame (id) values ('12');
INSERT INTO DatumReferenceFrames (__DatumReferenceFrame) values ('{1,2,3}');
INSERT INTO DatumDefinition (id,DatumLabel) values ('51','A');
INSERT INTO DatumDefinition (id,DatumLabel) values ('51','A');
INSERT INTO DatumDefinition (id,DatumLabel) values ('51','A');
INSERT INTO DatumDefinition (id,DatumLabel) values ('51','A');
INSERT INTO DatumDefinition (id,DatumLabel) values ('51','A');
INSERT INTO DatumDefinitions (__DatumDefinition) values ('{1,2,3,4,5}');
INSERT INTO FormalStandard (FormalStandardEnum) values ('ASME-Y14.5-1994');
INSERT INTO PositionCharacteristicNominal (id,CharacteristicDefinitionId) values ('54',49);
INSERT INTO PositionCharacteristicNominal (id,CharacteristicDefinitionId) values ('54',49);
INSERT INTO PointProfileCharacteristicNominal (id,CharacteristicDefinitionId) values ('13',11);
INSERT INTO PointProfileCharacteristicNominal (id,CharacteristicDefinitionId) values ('13',11);
INSERT INTO LinearCoordinateCharacteristicNominal (id,CharacteristicDefinitionId,Direction,TargetValue) values ('22',21,'XAXIS',2466.729248046875);
INSERT INTO LinearCoordinateCharacteristicNominal (id,CharacteristicDefinitionId,Direction,TargetValue) values ('22',21,'XAXIS',2466.729248046875);
INSERT INTO LinearCoordinateCharacteristicNominal (id,CharacteristicDefinitionId,Direction,TargetValue) values ('22',21,'XAXIS',2466.729248046875);
INSERT INTO DistanceBetweenCharacteristicNominal (id,AnalysisMode,CharacteristicDefinitionId,TargetValue) values ('83','THREEDIMENSIONAL',82,81.208839738425993);
INSERT INTO DiameterCharacteristicNominal (id,CharacteristicDefinitionId,TargetValue) values ('46',45,10);
INSERT INTO DiameterCharacteristicNominal (id,CharacteristicDefinitionId,TargetValue) values ('46',45,10);
INSERT INTO DiameterCharacteristicNominal (id,CharacteristicDefinitionId,TargetValue) values ('46',45,10);
INSERT INTO CharacteristicNominals (__DiameterCharacteristicNominal,__DistanceBetweenCharacteristicNominal,__LinearCoordinateCharacteristicNominal,__PointProfileCharacteristicNominal,__PositionCharacteristicNominal) values ('{1,2,3}','{1}','{1,2,3}','{1,2}','{1,2}');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"56"}');
INSERT INTO LocationOnDrawing (DrawingId,DrawingZone,SheetNumber) values (5,'C1','SHEET1');
INSERT INTO KeyCharacteristic (Criticality,Designator) values ('CRITICAL','7');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"43"}');
INSERT INTO AttributeStr (value,name) values ('MMC diametrical position to AB(m)C(m)','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{31}');
INSERT INTO PositionCharacteristicItem (id,_Attributes,CharacteristicNominalId,_FeatureItemIds,_KeyCharacteristic,_LocationOnDrawing,_MeasurementDeviceIds,Name,QPId) values ('55',21,54,41,21,21,42,'7','4438e85a-441a-420f-93d8-c6ed52fae87e');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"56"}');
INSERT INTO LocationOnDrawing (DrawingId,DrawingZone,SheetNumber) values (5,'C1','SHEET1');
INSERT INTO KeyCharacteristic (Criticality,Designator) values ('CRITICAL','7');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"43"}');
INSERT INTO AttributeStr (value,name) values ('MMC diametrical position to AB(m)C(m)','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{28}');
INSERT INTO PositionCharacteristicItem (id,_Attributes,CharacteristicNominalId,_FeatureItemIds,_KeyCharacteristic,_LocationOnDrawing,_MeasurementDeviceIds,Name,QPId) values ('55',19,54,37,19,19,38,'7','4438e85a-441a-420f-93d8-c6ed52fae87e');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"15"}');
INSERT INTO LocationOnDrawing (DrawingId,DrawingZone,SheetNumber) values (5,'C2','SHEET1');
INSERT INTO KeyCharacteristic (Criticality,Designator) values ('MINOR','5');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"9"}');
INSERT INTO AttributeStr (value,name) values ('A uniform profile zone ±2.0 with empty DRF','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{25}');
INSERT INTO PointProfileCharacteristicItem (id,_Attributes,CharacteristicNominalId,_FeatureItemIds,_KeyCharacteristic,_LocationOnDrawing,_MeasurementDeviceIds,Name,QPId) values ('14',17,13,33,17,17,34,'5','6f2a6f83-3ff7-4327-b00c-98208361301a');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"15"}');
INSERT INTO LocationOnDrawing (DrawingId,DrawingZone,SheetNumber) values (5,'C2','SHEET1');
INSERT INTO KeyCharacteristic (Criticality,Designator) values ('MINOR','5');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"9"}');
INSERT INTO AttributeStr (value,name) values ('A uniform profile zone ±2.0 with empty DRF','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{22}');
INSERT INTO PointProfileCharacteristicItem (id,_Attributes,CharacteristicNominalId,_FeatureItemIds,_KeyCharacteristic,_LocationOnDrawing,_MeasurementDeviceIds,Name,QPId) values ('14',15,13,29,15,15,30,'5','6f2a6f83-3ff7-4327-b00c-98208361301a');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"15"}');
INSERT INTO LocationOnDrawing (DrawingId,DrawingZone,SheetNumber) values (5,'D3','SHEET1');
INSERT INTO KeyCharacteristic (Criticality,Designator) values ('REF','1');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"19"}');
INSERT INTO AttributeStr (value,name) values ('A basic coordinate dimension','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{19}');
INSERT INTO LinearCoordinateCharacteristicItem (id,_Attributes,CharacteristicNominalId,_FeatureItemIds,_KeyCharacteristic,_LocationOnDrawing,_MeasurementDeviceIds,Name,QPId) values ('23',13,22,25,13,13,26,'1','fdb07604-ac7e-4f7c-acc8-0860de517fd4');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"15"}');
INSERT INTO LocationOnDrawing (DrawingId,DrawingZone,SheetNumber) values (5,'D3','SHEET1');
INSERT INTO KeyCharacteristic (Criticality,Designator) values ('REF','1');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"19"}');
INSERT INTO AttributeStr (value,name) values ('A basic coordinate dimension','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{16}');
INSERT INTO LinearCoordinateCharacteristicItem (id,_Attributes,CharacteristicNominalId,_FeatureItemIds,_KeyCharacteristic,_LocationOnDrawing,_MeasurementDeviceIds,Name,QPId) values ('23',11,22,21,11,11,22,'1','fdb07604-ac7e-4f7c-acc8-0860de517fd4');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"15"}');
INSERT INTO LocationOnDrawing (DrawingId,DrawingZone,SheetNumber) values (5,'D3','SHEET1');
INSERT INTO KeyCharacteristic (Criticality,Designator) values ('REF','1');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"19"}');
INSERT INTO AttributeStr (value,name) values ('A basic coordinate dimension','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{13}');
INSERT INTO LinearCoordinateCharacteristicItem (id,_Attributes,CharacteristicNominalId,_FeatureItemIds,_KeyCharacteristic,_LocationOnDrawing,_MeasurementDeviceIds,Name,QPId) values ('23',9,22,17,9,9,18,'1','fdb07604-ac7e-4f7c-acc8-0860de517fd4');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"15"}');
INSERT INTO LocationOnDrawing (DrawingId,DrawingZone,SheetNumber) values (5,'B2','SHEET1');
INSERT INTO KeyCharacteristic (Criticality,Designator) values ('CRITICAL','11');
INSERT INTO ArrayReferenceFull (N,Id) values ('2','{"60","60"}');
INSERT INTO AttributeStr (value,name) values ('Distance between HOLE1 and HOLE2','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{10}');
INSERT INTO DistanceBetweenCharacteristicItem (id,_Attributes,CharacteristicNominalId,_FeatureItemIds,_KeyCharacteristic,_LocationOnDrawing,_MeasurementDeviceIds,Name,QPId) values ('84',7,83,13,7,7,14,'DIST1','3e6797f5-b443-4b15-9108-055190223837');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"15"}');
INSERT INTO LocationOnDrawing (DrawingId,DrawingZone,SheetNumber) values (5,'C1','SHEET1');
INSERT INTO KeyCharacteristic (Criticality,Designator) values ('MINOR','6');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"43"}');
INSERT INTO AttributeStr (value,name) values ('A bi-directional diameter tolerance','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{7}');
INSERT INTO DiameterCharacteristicItem (id,_Attributes,CharacteristicNominalId,_FeatureItemIds,_KeyCharacteristic,_LocationOnDrawing,_MeasurementDeviceIds,Name,QPId) values ('47',5,46,9,5,5,10,'6','4e609ab8-7d1c-4317-9b16-5fea194f9d7e');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"15"}');
INSERT INTO LocationOnDrawing (DrawingId,DrawingZone,SheetNumber) values (5,'C1','SHEET1');
INSERT INTO KeyCharacteristic (Criticality,Designator) values ('MINOR','6');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"43"}');
INSERT INTO AttributeStr (value,name) values ('A bi-directional diameter tolerance','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{4}');
INSERT INTO DiameterCharacteristicItem (id,_Attributes,CharacteristicNominalId,_FeatureItemIds,_KeyCharacteristic,_LocationOnDrawing,_MeasurementDeviceIds,Name,QPId) values ('47',3,46,5,3,3,6,'6','4e609ab8-7d1c-4317-9b16-5fea194f9d7e');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"15"}');
INSERT INTO LocationOnDrawing (DrawingId,DrawingZone,SheetNumber) values (5,'C1','SHEET1');
INSERT INTO KeyCharacteristic (Criticality,Designator) values ('MINOR','6');
INSERT INTO ArrayReferenceFull (N,Id) values ('1','{"43"}');
INSERT INTO AttributeStr (value,name) values ('A bi-directional diameter tolerance','Comment');
INSERT INTO Attributes (N,__AttributeStr) values ('1','{1}');
INSERT INTO DiameterCharacteristicItem (id,_Attributes,CharacteristicNominalId,_FeatureItemIds,_KeyCharacteristic,_LocationOnDrawing,_MeasurementDeviceIds,Name,QPId) values ('47',1,46,1,1,1,2,'6','4e609ab8-7d1c-4317-9b16-5fea194f9d7e');
INSERT INTO CharacteristicItems (__DiameterCharacteristicItem,__DistanceBetweenCharacteristicItem,__LinearCoordinateCharacteristicItem,__PointProfileCharacteristicItem,__PositionCharacteristicItem) values ('{1,2,3}','{1}','{1,2,3}','{1,2}','{1,2}');
INSERT INTO PositionZoneShape (_DiametricalZone) values (0);
INSERT INTO PositionCharacteristicDefinition (id,DatumReferenceFrameId,MaterialCondition,ToleranceValue,_ZoneShape) values ('49',50,'MAXIMUM',1,3);
INSERT INTO PositionZoneShape (_DiametricalZone) values (0);
INSERT INTO PositionCharacteristicDefinition (id,DatumReferenceFrameId,MaterialCondition,ToleranceValue,_ZoneShape) values ('49',50,'MAXIMUM',1,1);
INSERT INTO PointProfileCharacteristicDefinition (id,DatumReferenceFrameId,ToleranceValue) values ('11',12,4);
INSERT INTO PointProfileCharacteristicDefinition (id,DatumReferenceFrameId,ToleranceValue) values ('11',12,4);
INSERT INTO LinearCoordinateCharacteristicDefinition (id,NonTolerance) values ('21','MEASURED');
INSERT INTO LinearCoordinateCharacteristicDefinition (id,NonTolerance) values ('21','MEASURED');
INSERT INTO LinearCoordinateCharacteristicDefinition (id,NonTolerance) values ('21','MEASURED');
INSERT INTO LinearTolerance (DefinedAsLimit,MaxValue,MinValue) values (false,0.5,-0.5);
INSERT INTO DistanceBetweenCharacteristicDefinition (id,_Tolerance) values ('82',7);
INSERT INTO LinearTolerance (DefinedAsLimit,MaxValue,MinValue) values (false,0.4,-0.4);
INSERT INTO DiameterCharacteristicDefinition (id,_Tolerance) values ('45',5);
INSERT INTO LinearTolerance (DefinedAsLimit,MaxValue,MinValue) values (false,0.4,-0.4);
INSERT INTO DiameterCharacteristicDefinition (id,_Tolerance) values ('45',3);
INSERT INTO LinearTolerance (DefinedAsLimit,MaxValue,MinValue) values (false,0.4,-0.4);
INSERT INTO DiameterCharacteristicDefinition (id,_Tolerance) values ('45',1);
INSERT INTO CharacteristicDefinitions (__DiameterCharacteristicDefinition,__DistanceBetweenCharacteristicDefinition,__LinearCoordinateCharacteristicDefinition,__PointProfileCharacteristicDefinition,__PositionCharacteristicDefinition) values ('{1,2,3}','{1}','{1,2,3}','{1,2}','{1,2}');
INSERT INTO CharacteristicAspectsLists (_CharacteristicDefinitions,_CharacteristicItems,_CharacteristicNominals,_FormalStandard) values (1,1,1,1);
INSERT INTO QIFDocument (versionQIF,idMax,_Characteristics,_DatumDefinitions,_DatumReferenceFrames,_Features,_FileUnits,_Header,_MeasurementResources,_MeasurementsResults,_PreInspectionTraceability,_Product,_Version) values ('2.0.0','86',1,1,1,1,1,1,1,1,1,1,1);

