// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef PRIMITIVES_PD_HXX
#define PRIMITIVES_PD_HXX

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 4000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

#include <xsd/cxx/tree/parsing.hxx>
#include <xsd/cxx/tree/parsing/byte.hxx>
#include <xsd/cxx/tree/parsing/unsigned-byte.hxx>
#include <xsd/cxx/tree/parsing/short.hxx>
#include <xsd/cxx/tree/parsing/unsigned-short.hxx>
#include <xsd/cxx/tree/parsing/int.hxx>
#include <xsd/cxx/tree/parsing/unsigned-int.hxx>
#include <xsd/cxx/tree/parsing/long.hxx>
#include <xsd/cxx/tree/parsing/unsigned-long.hxx>
#include <xsd/cxx/tree/parsing/boolean.hxx>
#include <xsd/cxx/tree/parsing/float.hxx>
#include <xsd/cxx/tree/parsing/double.hxx>
#include <xsd/cxx/tree/parsing/decimal.hxx>

#include <xsd/cxx/xml/dom/serialization-header.hxx>
#include <xsd/cxx/tree/serialization.hxx>
#include <xsd/cxx/tree/serialization/byte.hxx>
#include <xsd/cxx/tree/serialization/unsigned-byte.hxx>
#include <xsd/cxx/tree/serialization/short.hxx>
#include <xsd/cxx/tree/serialization/unsigned-short.hxx>
#include <xsd/cxx/tree/serialization/int.hxx>
#include <xsd/cxx/tree/serialization/unsigned-int.hxx>
#include <xsd/cxx/tree/serialization/long.hxx>
#include <xsd/cxx/tree/serialization/unsigned-long.hxx>
#include <xsd/cxx/tree/serialization/boolean.hxx>
#include <xsd/cxx/tree/serialization/float.hxx>
#include <xsd/cxx/tree/serialization/double.hxx>
#include <xsd/cxx/tree/serialization/decimal.hxx>

namespace xml_schema
{
  // anyType and anySimpleType.
  //
  typedef ::xsd::cxx::tree::type type;
  typedef ::xsd::cxx::tree::simple_type< char, type > simple_type;
  typedef ::xsd::cxx::tree::type container;

  // 8-bit
  //
  typedef signed char byte;
  typedef unsigned char unsigned_byte;

  // 16-bit
  //
  typedef short short_;
  typedef unsigned short unsigned_short;

  // 32-bit
  //
  typedef int int_;
  typedef unsigned int unsigned_int;

  // 64-bit
  //
  typedef long long long_;
  typedef unsigned long long unsigned_long;

  // Supposed to be arbitrary-length integral types.
  //
  typedef long long integer;
  typedef long long non_positive_integer;
  typedef unsigned long long non_negative_integer;
  typedef unsigned long long positive_integer;
  typedef long long negative_integer;

  // Boolean.
  //
  typedef bool boolean;

  // Floating-point types.
  //
  typedef float float_;
  typedef double double_;
  typedef double decimal;

  // String types.
  //
  typedef ::xsd::cxx::tree::string< char, simple_type > string;
  typedef ::xsd::cxx::tree::normalized_string< char, string > normalized_string;
  typedef ::xsd::cxx::tree::token< char, normalized_string > token;
  typedef ::xsd::cxx::tree::name< char, token > name;
  typedef ::xsd::cxx::tree::nmtoken< char, token > nmtoken;
  typedef ::xsd::cxx::tree::nmtokens< char, simple_type, nmtoken > nmtokens;
  typedef ::xsd::cxx::tree::ncname< char, name > ncname;
  typedef ::xsd::cxx::tree::language< char, token > language;

  // ID/IDREF.
  //
  typedef ::xsd::cxx::tree::id< char, ncname > id;
  typedef ::xsd::cxx::tree::idref< char, ncname, type > idref;
  typedef ::xsd::cxx::tree::idrefs< char, simple_type, idref > idrefs;

  // URI.
  //
  typedef ::xsd::cxx::tree::uri< char, simple_type > uri;

  // Qualified name.
  //
  typedef ::xsd::cxx::tree::qname< char, simple_type, uri, ncname > qname;

  // Binary.
  //
  typedef ::xsd::cxx::tree::buffer< char > buffer;
  typedef ::xsd::cxx::tree::base64_binary< char, simple_type > base64_binary;
  typedef ::xsd::cxx::tree::hex_binary< char, simple_type > hex_binary;

  // Date/time.
  //
  typedef ::xsd::cxx::tree::time_zone time_zone;
  typedef ::xsd::cxx::tree::date< char, simple_type > date;
  typedef ::xsd::cxx::tree::date_time< char, simple_type > date_time;
  typedef ::xsd::cxx::tree::duration< char, simple_type > duration;
  typedef ::xsd::cxx::tree::gday< char, simple_type > gday;
  typedef ::xsd::cxx::tree::gmonth< char, simple_type > gmonth;
  typedef ::xsd::cxx::tree::gmonth_day< char, simple_type > gmonth_day;
  typedef ::xsd::cxx::tree::gyear< char, simple_type > gyear;
  typedef ::xsd::cxx::tree::gyear_month< char, simple_type > gyear_month;
  typedef ::xsd::cxx::tree::time< char, simple_type > time;

  // Entity.
  //
  typedef ::xsd::cxx::tree::entity< char, ncname > entity;
  typedef ::xsd::cxx::tree::entities< char, simple_type, entity > entities;

  typedef ::xsd::cxx::tree::content_order content_order;
  // Namespace information and list stream. Used in
  // serialization functions.
  //
  typedef ::xsd::cxx::xml::dom::namespace_info< char > namespace_info;
  typedef ::xsd::cxx::xml::dom::namespace_infomap< char > namespace_infomap;
  typedef ::xsd::cxx::tree::list_stream< char > list_stream;
  typedef ::xsd::cxx::tree::as_double< double_ > as_double;
  typedef ::xsd::cxx::tree::as_decimal< decimal > as_decimal;
  typedef ::xsd::cxx::tree::facet facet;

  // Flags and properties.
  //
  typedef ::xsd::cxx::tree::flags flags;
  typedef ::xsd::cxx::tree::properties< char > properties;

  // Parsing/serialization diagnostics.
  //
  typedef ::xsd::cxx::tree::severity severity;
  typedef ::xsd::cxx::tree::error< char > error;
  typedef ::xsd::cxx::tree::diagnostics< char > diagnostics;

  // Exceptions.
  //
  typedef ::xsd::cxx::tree::exception< char > exception;
  typedef ::xsd::cxx::tree::bounds< char > bounds;
  typedef ::xsd::cxx::tree::duplicate_id< char > duplicate_id;
  typedef ::xsd::cxx::tree::parsing< char > parsing;
  typedef ::xsd::cxx::tree::expected_element< char > expected_element;
  typedef ::xsd::cxx::tree::unexpected_element< char > unexpected_element;
  typedef ::xsd::cxx::tree::expected_attribute< char > expected_attribute;
  typedef ::xsd::cxx::tree::unexpected_enumerator< char > unexpected_enumerator;
  typedef ::xsd::cxx::tree::expected_text_content< char > expected_text_content;
  typedef ::xsd::cxx::tree::no_prefix_mapping< char > no_prefix_mapping;
  typedef ::xsd::cxx::tree::no_type_info< char > no_type_info;
  typedef ::xsd::cxx::tree::not_derived< char > not_derived;
  typedef ::xsd::cxx::tree::serialization< char > serialization;

  // Error handler callback interface.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;

  // DOM interaction.
  //
  namespace dom
  {
    // Automatic pointer for DOMDocument.
    //
    using ::xsd::cxx::xml::dom::auto_ptr;

#ifndef XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
    // DOM user data key for back pointers to tree nodes.
    //
    const XMLCh* const tree_node_key = ::xsd::cxx::tree::user_data_keys::node;
#endif
  }
}

// Forward declarations.
//
namespace xsd
{
  namespace qif2
  {
    class ColorType;
    class ListDouble9Type;
    class Matrix33Type;
    class QuaternionType;
    class NodeBaseType;
    class NodeWithIdBaseType;
    class DrawableBaseType;
    class AuthorType;
    class ApplicationType;
  }
}


#include <memory>    // ::std::auto_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "../QIFLibrary/Primitives.hxx"

namespace xsd
{
  namespace qif2
  {
    class ColorType: public ::xsd::qif2::ListIntType
    {
      public:
      // Constructors.
      //
      ColorType ();

      ColorType (const ::xsd::qif2::ListIntType&);

      ColorType (const ::xercesc::DOMElement& e,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

      ColorType (const ::xercesc::DOMAttr& a,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

      ColorType (const ::std::string& s,
                 const ::xercesc::DOMElement* e,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

      ColorType (const ColorType& x,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

      virtual ColorType*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      virtual 
      ~ColorType ();
    };

    class ListDouble9Type: public ::xsd::qif2::ListDoubleType
    {
      public:
      // Constructors.
      //
      ListDouble9Type ();

      ListDouble9Type (const ::xsd::qif2::ListDoubleType&);

      ListDouble9Type (const ::xercesc::DOMElement& e,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

      ListDouble9Type (const ::xercesc::DOMAttr& a,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

      ListDouble9Type (const ::std::string& s,
                       const ::xercesc::DOMElement* e,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

      ListDouble9Type (const ListDouble9Type& x,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

      virtual ListDouble9Type*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      virtual 
      ~ListDouble9Type ();
    };

    class Matrix33Type: public ::xsd::qif2::ListDouble9Type
    {
      public:
      // Constructors.
      //
      Matrix33Type ();

      Matrix33Type (const ::xsd::qif2::ListDoubleType&);

      Matrix33Type (const ::xercesc::DOMElement& e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

      Matrix33Type (const ::xercesc::DOMAttr& a,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

      Matrix33Type (const ::std::string& s,
                    const ::xercesc::DOMElement* e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

      Matrix33Type (const Matrix33Type& x,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

      virtual Matrix33Type*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      virtual 
      ~Matrix33Type ();
    };

    class QuaternionType: public ::xml_schema::type
    {
      public:
      // Value
      //
      typedef ::xsd::qif2::D4Type Value_type;
      typedef ::xsd::cxx::tree::traits< Value_type, char > Value_traits;

      const Value_type&
      Value () const;

      Value_type&
      Value ();

      void
      Value (const Value_type& x);

      void
      Value (::std::auto_ptr< Value_type > p);

      // Constructors.
      //
      QuaternionType (const Value_type&);

      QuaternionType (const ::xercesc::DOMElement& e,
                      ::xml_schema::flags f = 0,
                      ::xml_schema::container* c = 0);

      QuaternionType (const QuaternionType& x,
                      ::xml_schema::flags f = 0,
                      ::xml_schema::container* c = 0);

      virtual QuaternionType*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      QuaternionType&
      operator= (const QuaternionType& x);

      virtual 
      ~QuaternionType ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      ::xsd::cxx::tree::one< Value_type > Value_;
    };

    class NodeBaseType: public ::xml_schema::type
    {
      public:
      // label
      //
      typedef ::xml_schema::string label_type;
      typedef ::xsd::cxx::tree::optional< label_type > label_optional;
      typedef ::xsd::cxx::tree::traits< label_type, char > label_traits;

      const label_optional&
      label () const;

      label_optional&
      label ();

      void
      label (const label_type& x);

      void
      label (const label_optional& x);

      void
      label (::std::auto_ptr< label_type > p);

      // Constructors.
      //
      NodeBaseType ();

      NodeBaseType (const ::xercesc::DOMElement& e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

      NodeBaseType (const NodeBaseType& x,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

      virtual NodeBaseType*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      NodeBaseType&
      operator= (const NodeBaseType& x);

      virtual 
      ~NodeBaseType ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      label_optional label_;
    };

    class NodeWithIdBaseType: public ::xsd::qif2::NodeBaseType
    {
      public:
      // Attributes
      //
      typedef ::xsd::qif2::AttributesType Attributes_type;
      typedef ::xsd::cxx::tree::optional< Attributes_type > Attributes_optional;
      typedef ::xsd::cxx::tree::traits< Attributes_type, char > Attributes_traits;

      const Attributes_optional&
      Attributes () const;

      Attributes_optional&
      Attributes ();

      void
      Attributes (const Attributes_type& x);

      void
      Attributes (const Attributes_optional& x);

      void
      Attributes (::std::auto_ptr< Attributes_type > p);

      // id
      //
      typedef ::xsd::qif2::QIFIdType id_type;
      typedef ::xsd::cxx::tree::traits< id_type, char > id_traits;

      const id_type&
      id () const;

      id_type&
      id ();

      void
      id (const id_type& x);

      void
      id (::std::auto_ptr< id_type > p);

      // Constructors.
      //
      NodeWithIdBaseType (const id_type&);

      NodeWithIdBaseType (const ::xercesc::DOMElement& e,
                          ::xml_schema::flags f = 0,
                          ::xml_schema::container* c = 0);

      NodeWithIdBaseType (const NodeWithIdBaseType& x,
                          ::xml_schema::flags f = 0,
                          ::xml_schema::container* c = 0);

      virtual NodeWithIdBaseType*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      NodeWithIdBaseType&
      operator= (const NodeWithIdBaseType& x);

      virtual 
      ~NodeWithIdBaseType ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      Attributes_optional Attributes_;
      ::xsd::cxx::tree::one< id_type > id_;
    };

    class DrawableBaseType: public ::xsd::qif2::NodeWithIdBaseType
    {
      public:
      // color
      //
      typedef ::xsd::qif2::ColorType color_type;
      typedef ::xsd::cxx::tree::optional< color_type > color_optional;
      typedef ::xsd::cxx::tree::traits< color_type, char > color_traits;

      const color_optional&
      color () const;

      color_optional&
      color ();

      void
      color (const color_type& x);

      void
      color (const color_optional& x);

      void
      color (::std::auto_ptr< color_type > p);

      // transparency
      //
      typedef ::xml_schema::double_ transparency_type;
      typedef ::xsd::cxx::tree::traits< transparency_type, char, ::xsd::cxx::tree::schema_type::double_ > transparency_traits;

      const transparency_type&
      transparency () const;

      transparency_type&
      transparency ();

      void
      transparency (const transparency_type& x);

      static transparency_type
      transparency_default_value ();

      // hidden
      //
      typedef ::xml_schema::boolean hidden_type;
      typedef ::xsd::cxx::tree::traits< hidden_type, char > hidden_traits;

      const hidden_type&
      hidden () const;

      hidden_type&
      hidden ();

      void
      hidden (const hidden_type& x);

      static hidden_type
      hidden_default_value ();

      // size
      //
      typedef ::xsd::qif2::DoublePositiveType size_type;
      typedef ::xsd::cxx::tree::optional< size_type > size_optional;
      typedef ::xsd::cxx::tree::traits< size_type, char > size_traits;

      const size_optional&
      size () const;

      size_optional&
      size ();

      void
      size (const size_type& x);

      void
      size (const size_optional& x);

      void
      size (::std::auto_ptr< size_type > p);

      // Constructors.
      //
      DrawableBaseType (const id_type&);

      DrawableBaseType (const ::xercesc::DOMElement& e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

      DrawableBaseType (const DrawableBaseType& x,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

      virtual DrawableBaseType*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      DrawableBaseType&
      operator= (const DrawableBaseType& x);

      virtual 
      ~DrawableBaseType ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      color_optional color_;
      ::xsd::cxx::tree::one< transparency_type > transparency_;
      ::xsd::cxx::tree::one< hidden_type > hidden_;
      size_optional size_;
    };

    class AuthorType: public ::xml_schema::type
    {
      public:
      // Name
      //
      typedef ::xml_schema::string Name_type;
      typedef ::xsd::cxx::tree::optional< Name_type > Name_optional;
      typedef ::xsd::cxx::tree::traits< Name_type, char > Name_traits;

      const Name_optional&
      Name () const;

      Name_optional&
      Name ();

      void
      Name (const Name_type& x);

      void
      Name (const Name_optional& x);

      void
      Name (::std::auto_ptr< Name_type > p);

      // Organization
      //
      typedef ::xml_schema::string Organization_type;
      typedef ::xsd::cxx::tree::optional< Organization_type > Organization_optional;
      typedef ::xsd::cxx::tree::traits< Organization_type, char > Organization_traits;

      const Organization_optional&
      Organization () const;

      Organization_optional&
      Organization ();

      void
      Organization (const Organization_type& x);

      void
      Organization (const Organization_optional& x);

      void
      Organization (::std::auto_ptr< Organization_type > p);

      // Constructors.
      //
      AuthorType ();

      AuthorType (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

      AuthorType (const AuthorType& x,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

      virtual AuthorType*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      AuthorType&
      operator= (const AuthorType& x);

      virtual 
      ~AuthorType ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      Name_optional Name_;
      Organization_optional Organization_;
    };

    class ApplicationType: public ::xml_schema::type
    {
      public:
      // Name
      //
      typedef ::xml_schema::string Name_type;
      typedef ::xsd::cxx::tree::traits< Name_type, char > Name_traits;

      const Name_type&
      Name () const;

      Name_type&
      Name ();

      void
      Name (const Name_type& x);

      void
      Name (::std::auto_ptr< Name_type > p);

      // Organization
      //
      typedef ::xml_schema::string Organization_type;
      typedef ::xsd::cxx::tree::optional< Organization_type > Organization_optional;
      typedef ::xsd::cxx::tree::traits< Organization_type, char > Organization_traits;

      const Organization_optional&
      Organization () const;

      Organization_optional&
      Organization ();

      void
      Organization (const Organization_type& x);

      void
      Organization (const Organization_optional& x);

      void
      Organization (::std::auto_ptr< Organization_type > p);

      // AddonName
      //
      typedef ::xml_schema::string AddonName_type;
      typedef ::xsd::cxx::tree::optional< AddonName_type > AddonName_optional;
      typedef ::xsd::cxx::tree::traits< AddonName_type, char > AddonName_traits;

      const AddonName_optional&
      AddonName () const;

      AddonName_optional&
      AddonName ();

      void
      AddonName (const AddonName_type& x);

      void
      AddonName (const AddonName_optional& x);

      void
      AddonName (::std::auto_ptr< AddonName_type > p);

      // AddonOrganization
      //
      typedef ::xml_schema::string AddonOrganization_type;
      typedef ::xsd::cxx::tree::optional< AddonOrganization_type > AddonOrganization_optional;
      typedef ::xsd::cxx::tree::traits< AddonOrganization_type, char > AddonOrganization_traits;

      const AddonOrganization_optional&
      AddonOrganization () const;

      AddonOrganization_optional&
      AddonOrganization ();

      void
      AddonOrganization (const AddonOrganization_type& x);

      void
      AddonOrganization (const AddonOrganization_optional& x);

      void
      AddonOrganization (::std::auto_ptr< AddonOrganization_type > p);

      // Constructors.
      //
      ApplicationType (const Name_type&);

      ApplicationType (const ::xercesc::DOMElement& e,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

      ApplicationType (const ApplicationType& x,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

      virtual ApplicationType*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      ApplicationType&
      operator= (const ApplicationType& x);

      virtual 
      ~ApplicationType ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      ::xsd::cxx::tree::one< Name_type > Name_;
      Organization_optional Organization_;
      AddonName_optional AddonName_;
      AddonOrganization_optional AddonOrganization_;
    };
  }
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace xsd
{
  namespace qif2
  {
  }
}

#include <iosfwd>

#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>
#include <xercesc/framework/XMLFormatter.hpp>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

namespace xsd
{
  namespace qif2
  {
    void
    operator<< (::xercesc::DOMElement&, const ColorType&);

    void
    operator<< (::xercesc::DOMAttr&, const ColorType&);

    void
    operator<< (::xml_schema::list_stream&,
                const ColorType&);

    void
    operator<< (::xercesc::DOMElement&, const ListDouble9Type&);

    void
    operator<< (::xercesc::DOMAttr&, const ListDouble9Type&);

    void
    operator<< (::xml_schema::list_stream&,
                const ListDouble9Type&);

    void
    operator<< (::xercesc::DOMElement&, const Matrix33Type&);

    void
    operator<< (::xercesc::DOMAttr&, const Matrix33Type&);

    void
    operator<< (::xml_schema::list_stream&,
                const Matrix33Type&);

    void
    operator<< (::xercesc::DOMElement&, const QuaternionType&);

    void
    operator<< (::xercesc::DOMElement&, const NodeBaseType&);

    void
    operator<< (::xercesc::DOMElement&, const NodeWithIdBaseType&);

    void
    operator<< (::xercesc::DOMElement&, const DrawableBaseType&);

    void
    operator<< (::xercesc::DOMElement&, const AuthorType&);

    void
    operator<< (::xercesc::DOMElement&, const ApplicationType&);
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // PRIMITIVES_PD_HXX
